### ISSUE TITLE
ONFOOT Label Enhancement :)

### ISSUE THREAD

**Issue by Anonymous-any** [DeckerMMIV/FarmSim_Mod_QuickCamera#18]
Hello I am trying to add in inputBinding.xml "ONFOOT VEHICLE" on QuickCamRight and QuickCamLeft option and maybe QuickCamForward and QuickCamBackward but seem have no effect have you a way to enable it if possible?

PS: not related :) have you possibility to continue patch the AutoDrive/pulls you made few times ago :/
Best Regards a follower

**Comment by DeckerMMIV** [comment]
Unfortunately QuickCamera isn't designed for when the player avatar is 'on foot'.

Any particular reason why you want QuickCamera to support 'ONFOOT' and out-of-vehicle? I suppose you are using mainly keyboard, since you're experimenting with adding 'ONFOOT', but please try to explain a bit more what it is you try to accomplish.

**Comment by Anonymous-any** [comment]
Hi, thanks for reply yes Keyboard(because it's needed for most usage) :), mouse when i can't do by other way or fast move like mouseSensitivityScaleX="7.000000" mouseSensitivityScaleY="7.000000" and joystick ! it's was for use fast turn 45° left and right or 180° with joystick pad (not analog) ONFOOT of course because ONVEHICLE already work fine. And QuickCamForward and QuickCamBackward was for fast 180° always to try to use with pad (not analog) where i'm BUTTON_17 to BUTTON_20 cross pad you know.
Br

**Comment by DeckerMMIV** [comment]
Try the version 1.1.0.25 which I have just committed to GitHub. - I've added three new input-bindings, where only the 'u-turn' is default set to the 'END' key. The others you need to specify yourself.
![fsscreen_2017_07_26_18_34_02-b](https://user-images.githubusercontent.com/2834184/28632532-2d965956-7231-11e7-9d59-0c1e654d583e.png)

**Comment by Anonymous-any** [comment]
I love you ^-° I try this in the crowd many many thank Maestro Dev !
Br

**Comment by Anonymous-any** [comment]
Back to confirm (passed the night on the game :)) It's perfect really I hope other will use these functions, I mean I hope not to be the only one to have wanted these uses.
Best regard
