### ISSUE TITLE
Add option to automatically flip camera 180° when driving direction is changed from forward to reverse?

### ISSUE THREAD

**Issue by fdanapfel** [DeckerMMIV/FarmSim_Mod_QuickCamera#34]
I really like this mod, but it has been missing one feature for me so far: the option to automatically have the camera flib 180° when the driving direction is changed, so that you are looking back when driving in reverse without having to press a key.

This was the reason why I switched to using VCA in FS17 and FS19, but I really didn't need most of the other features of VCA.

Therefore it would be great if this could be added as an option in the QuickCamera mod for FS22.

**Comment by DeckerMMIV** [comment]
Hi @fdanapfel

Now that my mod have finally appeared on GIANTS Software's ModHub for FS22, I can take a look at your suggestion.

Personally I have not tried the 'Vehicle Control Addon' mod, but I know of it.

So what you are looking for, is basically a "one button" that do two actions simultaneously;
- toggles the driving direction,
- flips/rotates the vehicle's currently selected camera[*] towards the driving direction.

[*] By "currently selected camera", I mean that if you switch between the vehicle's inside and external camera, then only the camera that was active, at the time of "pressing the one button", will be affected.

If I can find the location(s) in the script code, where GIANTS Software does the "toggle driving direction", then I think it can be done with "one button".

**Comment by DeckerMMIV** [comment]
@fdanapfel - a preliminary beta of this is now available in the `master` branch.
I hope you know how to download here from GitHub and place in your mods folder.

There is now a (very raw) new control action, called `QuickCamDirectionChangeFlipCamera` in the list of Quick Camera actions, that you need to bind to a key. - In case you bind it to the `Space` key, make sure to unbind the key from the vanilla `Change direction` action, otherwise there could be issues.

**Comment by fdanapfel** [comment]
@DeckerMMIV Thanks a lot for taking a look at this request and for adding it as an option to your mod.

I've tested the beta now and it mostly works as expected. For standard vehicles the driving direction and the camera view are switched as expected after assigning a button on my PS4 Controller to the QuickCamDirectionChangeFlipCamera action (after disabling the controls for the default 'Change Direction' action of the game).

But when using it with vehicles that have a 'reverse driving' feature, like the Valtra Valmet 8750 or any of the Komatsu or Ponsse Forestry machines, the camera starts to behave 'wonky' when the reverse driving feature is activated: when the the camera is switched around initially as expected (I'm guessing this is part of the 'reverse driving' feature), but when the driving direction is then changed the camera isn't flipped on the first occasion, and afterwards it is flipped every time the driving direction changes, so you end up looking in the opposite direction as you are actually driving. When the reverse driving feature is disabled again then the camera starts to behave as expected again, i. e. it is flipped in the correct direction when changing the driving direction.
Hope this explanation makes halfway sense, its probably best to try this out for yourself to see what is going on.

Another small issue I've noticed is that the following warning appears in the log:
'  Warning: Missing l10n 'input_QuickCamDirectionChangeFlipCamera' in mod 'FS22_QuickCamera''

**Comment by DeckerMMIV** [comment]
@fdanapfel - I have modified the script code, so it now examines if it is a 'reverse driving' vehicle.

So the in-cabin (inside) camera now follow the driving direction, even when the seat has been rotated, when using the 'Change direction & Flip camera' action.

**Comment by fdanapfel** [comment]
@DeckerMMIV Just tested BETA-2, and everything seems to work as expected now.

Thanks again for adding this!

**Comment by THOMAS96-MODDING** [comment]
hello @DeckerMMIV!!
Will you add in a future update the function _**MOVEABLE CABIN CAMERA**_ come in Quick Camera FS19?
