### ISSUE TITLE
not working with Realistic Cab View mod enabled

### ISSUE THREAD

**Issue by mheric** [DeckerMMIV/FarmSim_Mod_QuickCamera#37]
The mod is not working with the Realistic Cab View mod enabled.

Leaning function would be amazing for quick camera mod.

**Comment by DeckerMMIV** [comment]
@mheric - Thank you for notifying me about this.

I have made a fix/work-around, so Quick Camera now works in conjunction with Realistic Cab View (FS22_CabView).

Though as this is not a "game-breaking issue", the GIANTS Software's ModHub guidelines states:
```
An Update for mods should only be done to fix game-breaking issues – otherwise there is a grace period 
of two weeks before we consider a submitted update for anything less than that (minor fixes, smaller 
feature additions, etc.). Do not submit an update to only change small things like the modDesc version.
```
So I will have to wait a while, before submitting this fix to the ModHub.

**Comment by mheric** [comment]
I just tried the latest version from this repository and it works. Thank you for the quick fix. Absolute legend!
