### ISSUE TITLE
Camera effecting other vehicles

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_QuickCamera#7]
When I use the keys to look forward or behind or 45/90 degrees and switch to another vehicle, the camera position is changed in other vehicles (but not all) as well

**Comment by DeckerMMIV** [comment]
I guess this happened with the [change 2.3.0](https://github.com/DeckerMMIV/FarmSim_Mod_QuickCamera/commit/6aaab3e554ac377716877c3caf0005d0b907e364).
I will look into it.

**Comment by DeckerMMIV** [comment]
@sootysax - Please verify if v2.4.1 solved the problem

**Comment by sootysax** [comment]
seems to have fixed the problem
